name: Go
on: [ push ]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go

      - run: go version

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: make test
